workspace(name = "fable_api")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# -- MAVEN --

RULES_JVM_EXTERNAL_TAG = "3.0"
RULES_JVM_EXTERNAL_SHA = "62133c125bf4109dfd9d2af64830208356ce4ef8b165a6ef15bbff7460b35c3a"

http_archive(
    name = "rules_jvm_external",
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
    sha256 = RULES_JVM_EXTERNAL_SHA,
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/%s.zip" % RULES_JVM_EXTERNAL_TAG,
)

load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    name = "maven",
    artifacts = [
        # kotlin
        "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.0",
        "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.0",

        # google
        "com.google.apis:google-api-services-sheets:v4-rev605-1.25.0",

        # firebase
        "com.google.firebase:firebase-admin:6.12.0",
        "io.grpc:grpc-core:1.23.0",
        "io.grpc:grpc-api:1.23.0",

        # ktor (server)
        "io.ktor:ktor-server-netty:1.3.0",
        "io.ktor:ktor-server:1.3.0",
        "io.ktor:ktor-server-core:1.3.0",
        "io.ktor:ktor-server-host-common:1.3.0",
        "io.ktor:ktor-client:1.3.0",
        "io.ktor:ktor-client-core:1.3.0",
        "io.ktor:ktor-client-logging:1.3.0",
        "io.ktor:ktor-client-json:1.3.0",
        "io.ktor:ktor-client-gson:1.3.0",
        "io.ktor:ktor-client-cio:1.3.0",
        "io.ktor:ktor-client-serialization:1.3.0",
        "io.ktor:ktor-http:1.3.0",
        "io.ktor:ktor-http-cio:1.3.0",
        "io.ktor:ktor-gson:1.3.0",
        "io.ktor:ktor-locations:1.3.0",
        "io.ktor:ktor-features:1.3.0",

        # deps
        "org.slf4j:slf4j-simple:2.0.0-alpha0",
    ],
    repositories = [
        # Private repositories are supported through HTTP Basic auth
        "https://repo1.maven.org/maven2/",
        "https://jcenter.bintray.com/",
        "https://mvnrepository.com/artifact/"
    ],
    version_conflict_policy = "pinned",
    fetch_sources = True,
    strict_visibility = True,
    fail_on_missing_checksum = True,
    use_unsafe_shared_cache = False,
    generate_compat_repositories = True,
    maven_install_json = "@fable_api//:maven_install.json",
)

#load("@maven//:defs.bzl", "pinned_maven_install")
#pinned_maven_install()
#
#load("@maven//:compat.bzl", "compat_repositories")
#compat_repositories()

# -- KOTLIN --

COMPILER_RELEASE = {
    "urls": [
        "https://github.com/JetBrains/kotlin/releases/download/v1.3.31/kotlin-compiler-1.3.31.zip",
    ],
    "sha256": "107325d56315af4f59ff28db6837d03c2660088e3efeb7d4e41f3e01bb848d6a",
}

rules_kotlin_version = "legacy-1.3.0-rc4"
rules_kotlin_sha = "fe32ced5273bcc2f9e41cea65a28a9184a77f3bc30fea8a5c47b3d3bfc801dff"

http_archive(
    name = "io_bazel_rules_kotlin",
    urls = ["https://github.com/bazelbuild/rules_kotlin/archive/%s.zip" % rules_kotlin_version],
    type = "zip",
    strip_prefix = "rules_kotlin-%s" % rules_kotlin_version,
    sha256 = rules_kotlin_sha,
)

load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kotlin_repositories", "kt_register_toolchains")
kotlin_repositories(compiler_release=COMPILER_RELEASE)
register_toolchains("//:kotlin_toolchain")
# kt_register_toolchains() # to use the default toolchain, otherwise see toolchains below

# -- KTOR --

load("@bazel_tools//tools/build_defs/repo:git.bzl", "new_git_repository")

#new_git_repository(
#  name = "ktor-remote",
#  remote = "https://github.com/googleapis/api-common-java.git",
#  tag = "1.7.0",
#  commit = "2dfa1798f0b026d781efd5e0bc4e6d9a5cfcec3e",
#  shallow_since = "1578993541 +0300",
#  build_file = "@//:BUILD.bazel"
#)
#
# new_git_repository(
#  name = "kotlin-remote",
#  remote = "https://github.com/Kotlin/anko-example.git",
#  commit = "4877e68f343fd6616bb983140f25a026efd5f301",
#  shallow_since = "1525446053 +0000",
#  build_file = "@//lib:BUILD.bazel"
# )

#jvm_maven_import_external(
#    name = "com_google_firebase_firebase_admin",
#    artifact = "com.google.firebase:firebase-admin:6.12.1",
#    jar_sha256 = "6db0c3a244c397429c2e362ea2837c3622d5b68bb95105d37c21c36e5bc70abf",
#    srcjar_sha256 = "b7ffb578b2bd6445c958356e308d1c46c9ea6fb868fc9444bc8bda3a41875a1b",
#    deps = [
#        "@com_google_code_findbugs_jsr305",
#        "@com_google_errorprone_error_prone_annotations",
#        "@com_google_j2objc_j2objc_annotations",
#        "@org_checkerframework_checker_qual",
#        "@org_codehaus_mojo_animal_sniffer_annotations"
#    ],
#)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_jar")

# openssl dgst -sha256

#http_jar(
#    name = "ktor_locations",
#    urls = [
#        "https://dl.bintray.com/kotlin/ktor/io/ktor/ktor-locations/1.3.0-rc3-1.3.70-eap-42/ktor-locations-1.3.0-rc3-1.3.70-eap-42.jar"
#    ],
#    sha256 = "74dcae7c7b6771bc3fc6efd4d1f171af578e48e9e8ab07699a3acb02568eb961",
#)

# ---------------------- DOCKER -----------------------------

# Download the rules_docker repository at release v0.14.1
http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "dc97fccceacd4c6be14e800b2a00693d5e8d07f69ee187babfd04a80a9f8e250",
    strip_prefix = "rules_docker-0.14.1",
    urls = ["https://github.com/bazelbuild/rules_docker/releases/download/v0.14.1/rules_docker-v0.14.1.tar.gz"],
)

load("@io_bazel_rules_docker//repositories:repositories.bzl", container_repositories = "repositories")
container_repositories()

# This is NOT needed when going through the language lang_image
# "repositories" function(s).
load("@io_bazel_rules_docker//repositories:deps.bzl", container_deps = "deps")

container_deps()

load("@io_bazel_rules_docker//container:container.bzl", "container_pull")

container_pull(
    name = "java_base",
    registry = "adoptopenjdk",
    repository = "openjdk12",
    digest = "sha256:d361cc4d0e9eb310a2bb05367636dc9ba0e0a22e21ef3f5f6b8fcd1aa708b3a0",
)

container_pull(
    name = "official_ubuntu",
    registry = "index.docker.io",
    repository = "library/ubuntu",
    digest = "sha256:d361cc4d0e9eb310a2bb05367636dc9ba0e0a22e21ef3f5f6b8fcd1aa708b3a0",
)


# Package Rules
http_archive(
    name = "rules_pkg",
    url = "https://github.com/bazelbuild/rules_pkg/releases/download/0.2.4/rules_pkg-0.2.4.tar.gz",
    sha256 = "4ba8f4ab0ff85f2484287ab06c0d871dcb31cc54d439457d28fd4ae14b18450a"
)
load("@rules_pkg//:deps.bzl", "rules_pkg_dependencies")
rules_pkg_dependencies()